### ISSUE TITLE
User created terms may require forum staff to approve them

### ISSUE THREAD

**Issue by Javier-Rotelli** [FriendsOfFlarum/taxonomies#1]
Hey, pretty much self explained.
If this option is enabled, user created terms would require someone with the right permission to approve it before appearing to the public

**Comment by clarkwinkelmann** [comment]
The extension is still under development at this point, sponsored by various clients.

This feature has been considered and requires several additional hours of development. It might be included in a future batch of sponsored features. 

Without sponsoring, it probably won't happen.
