### ISSUE TITLE
PDOException when enabling extension

### ISSUE THREAD

**Issue by imorland** [FriendsOfFlarum/taxonomies#2]
`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'flarum_fof_discussion_taxonomy_term_discussion_id_term_id_primary' is too long`

Flarum: 0.1.0-beta.13
PHP: 7.4.12
MySQL: 8.0.22
DB Prefix: `flarum_`

**Comment by clarkwinkelmann** [comment]
How do we want to handle those? It's definitely the prefix that causes the name to become too long.

We can shorten the name, but how short is short enough?

**Comment by imorland** [comment]
This is the local change I made, just to get it working for me.

`$table->primary(['discussion_id', 'term_id'], 'dtid_pri');`

And for good measure
```
$table->foreign('discussion_id', 'did_foriegn')->references('id')->on('discussions')->onDelete('cascade');
$table->foreign('term_id', 'tid_foriegn')->references('id')->on('fof_taxonomy_terms')->onDelete('cascade');
```
