### ISSUE TITLE
fof_discussion_taxonomy_term(errno: 150 "Foreign key constraint is incorrectly formed"

### ISSUE THREAD

**Issue by hrvoje-hr** [FriendsOfFlarum/taxonomies#3]
After table prefix removal  (https://github.com/FriendsOfFlarum/taxonomies/issues/2 ), still can't activate the extension.

From log:

`Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1005 Can't create table `mytable`.`fof_discussion_taxonomy_term` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `fof_discussion_taxonomy_term` add constraint `fof_discussion_taxonomy_term_term_id_foreign` foreign key (`term_id`) references `fof_taxonomy_terms` (`id`) on delete cascade) in /vendor/illuminate/database/Connection.php:664`

**Comment by clarkwinkelmann** [comment]
I see in the Discuss thread you say you use 10.3.27-MariaDB

I *think* the error references this line https://github.com/FriendsOfFlarum/taxonomies/blob/393340ab19bca059cda1b70138eaeb8e84ebf7b5/migrations/2020_09_28_create_discussion_term_table.php#L16

But I don't know what it could be. Maybe MariaDB needs the `onDelete` clause to be uppercase? Or maybe it also has something to do with a too long identifier.

**Comment by hrvoje-hr** [comment]
I don't even see the fof_taxonomy_terms table in my database. Only fof_discussion_taxonomy_term.

**Comment by clarkwinkelmann** [comment]
Did you delete the migrations which previously failed? (delete partial tables and the entries in `migrations` table)

You might need to start fresh if there were errors during the previous try.

**Comment by hrvoje-hr** [comment]
That did it. Thanks.

I suppose that this is not really an issue? Or at least it isn't once #2 is resolved?

**Comment by clarkwinkelmann** [comment]
I would say so, yes. Seems like it was because of the partially finished migrations from last error.

I'm closing the issue, but feel free to report again if you still experience issues!
